### ISSUE TITLE
Sort on missing field

### ISSUE THREAD

**Issue by Mogztter** [ReactiveMongo/ReactiveMongo#153]
I can do that in mongo shell: 
```sh
db.collection.find().sort({created: -1})
```

Where the field created is missing. But with Reactivemongo I get:
```
play.api.Application$$anon$1: Execution exception[[NoSuchElementException: JsError.get]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.1]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10.jar:2.2.1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10.jar:2.2.1]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
Caused by: java.util.NoSuchElementException: JsError.get
	at play.api.libs.json.JsError.get(JsResult.scala:11) ~[play-json_2.10.jar:2.2.1]
	at play.api.libs.json.JsError.get(JsResult.scala:10) ~[play-json_2.10.jar:2.2.1]
	at play.modules.reactivemongo.json.collection.JSONGenericHandlers$StructureBufferWriter$.write(jsoncollection.scala:44) ~[play2-reactivemongo_2.10-0.10.0.jar:0.10.0]
	at play.modules.reactivemongo.json.collection.JSONGenericHandlers$StructureBufferWriter$.write(jsoncollection.scala:42) ~[play2-reactivemongo_2.10-0.10.0.jar:0.10.0]
	at reactivemongo.api.collections.GenericQueryBuilder$class.reactivemongo$api$collections$GenericQueryBuilder$$write(genericcollection.scala:323) ~[reactivemongo_2.10-0.10.0.jar:0.10.0]
	at reactivemongo.api.collections.GenericQueryBuilder$class.cursor(genericcollection.scala:342) ~[reactivemongo_2.10-0.10.0.jar:0.10.0]
```

None of the following is working:
```scala
collection.genericQueryBuilder.copy(
  queryOption = Some(Json.obj()),
  sortOption = Some(Json.obj("created" -> -1)))
  .cursor[JsObject]
  .collect[List](size).map {
    list => Ok(Json.toJson(list))
  }
```

```scala
collection
  .find(Json.obj("$query" -> Json.obj(), "$orderby" -> Json.obj("created" -> -1)))
  .cursor[JsObject]
  .collect[List]().map {
    list => Ok(Json.toJson(list))
  }
```

```scala
collection
  .find(Json.obj())
  .sort(Json.obj("created" -> -1))
  .cursor[JsObject]
  .collect[List]().map {
    list => Ok(Json.toJson(list))
  }
```

Am I missing something ?

**Comment by cchantep** [comment]
See https://github.com/ReactiveMongo/Play-ReactiveMongo/pull/149
