### ISSUE TITLE
Unable to find documents using the $query operator with an empty query (JSError.get)

### ISSUE THREAD

**Issue by almeidap** [ReactiveMongo/ReactiveMongo#167]
When using the `$query` MongoDB operator with an empty query in order to find documents from a `JSONCollection`, a `NoSuchElementException` is thrown.

For example:

```
collection.find(
	Json.obj(
		"$query" -> Json.obj(),
		"$orderby" -> Json.obj("updated" -> -1)
	)
)
```

...throws:

```
[debug] application - Finding documents: [collection=users, query={"$query":{},"$orderby":{"updated":-1}}]
[error] application -

! @6hh6k68d7 - Internal server error, for (GET) [/users] ->

play.api.Application$$anon$1: Execution exception[[NoSuchElementException: JsError.get]]
        at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.2]
        at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.2]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10.jar:2.2.2]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10.jar:2.2.2]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
Caused by: java.util.NoSuchElementException: JsError.get
        at play.api.libs.json.JsError.get(JsResult.scala:11) ~[play-json_2.10.jar:2.2.2]
        at play.api.libs.json.JsError.get(JsResult.scala:10) ~[play-json_2.10.jar:2.2.2]
        at play.modules.reactivemongo.json.collection.JSONGenericHandlers$StructureBufferWriter$.write(jsoncollection.scala:44) ~[play2-reactivemongo_2.10-0.10.0.jar:0.10.0]
        at play.modules.reactivemongo.json.collection.JSONGenericHandlers$StructureBufferWriter$.write(jsoncollection.scala:42) ~[play2-reactivemongo_2.10-0.10.0.jar:0.10.0]
        at reactivemongo.api.collections.GenericQueryBuilder$class.reactivemongo$api$collections$GenericQueryBuilder$$write(genericcollection.scala:323) ~[reactivemongo_2.10-0.10.0.jar:0.10.0]
        at reactivemongo.api.collections.GenericQueryBuilder$class.cursor(genericcollection.scala:342) ~[reactivemongo_2.10-0.10.0.jar:0.10.0]
```

MongoDB empty queries seem to be allowed as per documentation:
http://docs.mongodb.org/manual/reference/operator/meta/query/#op._S_query
http://docs.mongodb.org/manual/reference/operator/meta/orderby/

Querying with a non-empty query works as expected:

```
collection.find(
	Json.obj(
		"$query" -> Json.obj("_id" -> Json.obj("$exists" -> true)),
		"$orderby" -> Json.obj("updated" -> -1)
	)
)
```

This seems to be a regression in the 0.10.0 release.

**Comment by cchantep** [comment]
This is working with next Play plugin for 0.11: https://github.com/ReactiveMongo/Play-ReactiveMongo/pull/115/files#diff-c3831b134298aeb236c72a942c3fafc3R120
