### ISSUE TITLE
Strange shutdown behavior

### ISSUE THREAD

**Issue by reid-spencer** [ReactiveMongo/ReactiveMongo#213]
I am trying to understand how to shut down (and restart) reactivemongo cleanly. I wrote [a little program](https://github.com/reid-spencer/ReactiveMongoLifecycle/blob/master/src/main/scala/reactiveMongoLifecycle.scala) which is very similar to the one in issue #162. It does nothing more than create a collection and then attempt to gracefully close the connection, driver and ActorSystem. If you pass it a number as an argument it will attempt to run that many times.  I turned up the logging to TRACE level and get some strange behavior from ReactiveMongo.  I think I've chosen to do things in a relatively simple way but I cannot get ReactiveMongo to shut down cleanly without dead letters, connections remaining or leaked threads. 

Specifically:
* There is a message: `reactivemongo.core.actors.MongoDBSystem - (State: Closing) UNHANDLED MESSAGE: ChannelConnected(-1223908403)` which looks incorrect. Perhaps this happens because the connection is closed so quickly after creating the connection?
* Message [reactivemongo.core.actors.Closed$] from Actor[akka://default/user/$b#-1287252929] to Actor[akka://default/deadLetters] was not delivered.  
* Message [reactivemongo.core.actors.Close$] from Actor[akka://default/user/$b#-1287252929] to Actor[akka://default/user/$a#63833639] was not delivered.
* Message [reactivemongo.core.actors.Close$] from Actor[akka://default/deadLetters] to Actor[akka://default/user/$b#-1287252929] was not delivered.
* After closing all the connections, the driver's list of connections reports one that is still open.
* A thread remains running after main exits, effectively hanging the program. This is likely a thread leak.

Of these, the last two are the most serious in my mind. It seems it is not possible to detect the condition when all connections have been closed. It also seems that there is a thread leak.

Before I break open YourKit on this, I thought I would ask if I'm doing things correctly. It seems the shutdown sequence is not well documented. 

```
[info] Running ReactiveMongoLifecycle 
11:46:09.605 INFO  [run-main-0] ReactiveMongoLifecycle$ - ~~~~~ Runnning Test #1 ~~~~~
11:46:09.903 INFO  [run-main-0] ReactiveMongoLifecycle$ - Create collection
11:46:09.914 DEBUG [run-main-0] ReactiveMongoLifecycle$ - Created foo collection and closed connection
11:46:09.917 DEBUG [default-akka.actor.default-dispatcher-2] reactivemongo.core.actors.MonitorActor - Monitor received Close
11:46:10.169 TRACE [default-akka.actor.default-dispatcher-3] reactivemongo.core.nodeset.ChannelFactory - created a new channel: [id: 0xb70ca3cd]
11:46:10.181 INFO  [default-akka.actor.default-dispatcher-3] reactivemongo.core.actors.MongoDBSystem - Received Close message, going to close connections and moving on stage Closing
11:46:10.184 TRACE [New I/O worker #1] reactivemongo.core.protocol.MongoHandler - (channel=-1223908403) connected
11:46:10.188 TRACE [New I/O worker #1] reactivemongo.core.protocol.MongoHandler - (channel=-1223908403) disconnected
11:46:10.189 TRACE [New I/O worker #1] reactivemongo.core.protocol.MongoHandler - (channel=-1223908403) closed
11:46:10.191 DEBUG [default-akka.actor.default-dispatcher-3] reactivemongo.core.actors.MongoDBSystem - Netty says all channels are closed.
11:46:10.199 ERROR [default-akka.actor.default-dispatcher-3] reactivemongo.core.actors.MongoDBSystem - (State: Closing) UNHANDLED MESSAGE: ChannelConnected(-1223908403)
11:46:10.203 DEBUG [default-akka.actor.default-dispatcher-3] reactivemongo.core.actors.MongoDBSystem - (State: Closing) Received ChannelDisconnected(-1223908403), remainingConnections = 1, disconnected = 1, connected = 0
11:46:10.206 DEBUG [default-akka.actor.default-dispatcher-3] reactivemongo.core.actors.MongoDBSystem - (State: Closing) Received ChannelClosed(-1223908403), remainingConnections = 0, disconnected = 0, connected = 0
11:46:10.208 INFO  [default-akka.actor.default-dispatcher-3] reactivemongo.core.actors.MongoDBSystem - MongoDBSystem Actor[akka://default/user/$a#63833639] is stopping.
11:46:10.208 DEBUG [default-akka.actor.default-dispatcher-2] reactivemongo.core.actors.MonitorActor - Monitor Actor[akka://default/user/$b#-1287252929] closed, stopping...
11:46:10.211 DEBUG [default-akka.actor.default-dispatcher-3] reactivemongo.core.actors.MongoDBSystem - Netty says all channels are closed.
11:46:10.212 WARN  [default-akka.actor.default-dispatcher-3] reactivemongo.core.actors.MongoDBSystem - MongoDBSystem Actor[akka://default/user/$a#63833639] stopped.
[INFO] [10/21/2014 11:46:10.213] [default-akka.actor.default-dispatcher-6] [akka://default/deadLetters] Message [reactivemongo.core.actors.Closed$] from Actor[akka://default/user/$b#-1287252929] to Actor[akka://default/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [10/21/2014 11:46:10.214] [default-akka.actor.default-dispatcher-6] [akka://default/user/$a] Message [reactivemongo.core.actors.Close$] from Actor[akka://default/user/$b#-1287252929] to Actor[akka://default/user/$a#63833639] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
11:46:10.215 DEBUG [default-akka.actor.default-dispatcher-2] reactivemongo.core.actors.MonitorActor - Monitor Actor[akka://default/user/$b#-1287252929] stopped.
11:46:11.919 DEBUG [run-main-0] ReactiveMongoLifecycle$ - Failed to close all mongoDB connections, 1 remain: 
java.util.concurrent.TimeoutException: Futures timed out after [2 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[scala-library.jar:?]
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) ~[scala-library.jar:?]
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107) ~[scala-library.jar:?]
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53) ~[scala-library.jar:?]
	at scala.concurrent.Await$.result(package.scala:107) ~[scala-library.jar:?]
	at ReactiveMongoLifecycle$$anonfun$2.apply$mcV$sp(reactiveMongoLifecycle.scala:36) ~[classes/:?]
	at ReactiveMongoLifecycle$$anonfun$2.apply(reactiveMongoLifecycle.scala:30) ~[classes/:?]
	at ReactiveMongoLifecycle$$anonfun$2.apply(reactiveMongoLifecycle.scala:30) ~[classes/:?]
	at scala.util.Try$.apply(Try.scala:161) ~[scala-library.jar:0.13.6]
	at ReactiveMongoLifecycle$.completeCycle(reactiveMongoLifecycle.scala:30) [classes/:?]
	at ReactiveMongoLifecycle$$anonfun$main$1.apply$mcVI$sp(reactiveMongoLifecycle.scala:60) [classes/:?]
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141) [scala-library.jar:0.13.6]
	at ReactiveMongoLifecycle$.main(reactiveMongoLifecycle.scala:58) [classes/:?]
	at ReactiveMongoLifecycle.main(reactiveMongoLifecycle.scala) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_17]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_17]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_17]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0_17]
	at sbt.Run.invokeMain(Run.scala:72) [run-0.13.5.jar:0.13.5]
	at sbt.Run.run0(Run.scala:65) [run-0.13.5.jar:0.13.5]
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54) [run-0.13.5.jar:0.13.5]
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58) [run-0.13.5.jar:0.13.5]
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58) [run-0.13.5.jar:0.13.5]
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58) [run-0.13.5.jar:0.13.5]
	at sbt.Logger$$anon$4.apply(Logger.scala:90) [logging-0.13.5.jar:0.13.5]
	at sbt.TrapExit$App.run(TrapExit.scala:244) [run-0.13.5.jar:0.13.5]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_17]
11:46:11.924 DEBUG [run-main-0] ReactiveMongoLifecycle$ - Connection remains open:reactivemongo.api.MongoConnection@660cf381
[INFO] [10/21/2014 11:46:11.925] [default-akka.actor.default-dispatcher-5] [akka://default/user/$b] Message [reactivemongo.core.actors.Close$] from Actor[akka://default/deadLetters] to Actor[akka://default/user/$b#-1287252929] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
11:46:11.940 DEBUG [run-main-0] ReactiveMongoLifecycle$ - The mongoDB driver has been closed.
11:46:11.940 INFO  [run-main-0] ReactiveMongoLifecycle$ - Done
^CReactiveMongoLifecycle reid$
```

**Comment by cchantep** [comment]
I guess this one can be closed (PR merged).
