### ISSUE TITLE
not authorized for query on heroku_app when app wakes up from sleep (sometimes)

### ISSUE THREAD

**Issue by francisdb** [ReactiveMongo/ReactiveMongo#361]
My heroku app is not used a lot. So most of the times when I open it the herkoku instance wakes up from sleep.
Sometimes my initial page does not load because of the error pasted below. Subsequent requests do succeed without problems. (see heroku log below)

using 0.11.2.play24
database running on mongolab

code at
https://github.com/francisdb/belgiantv

app runs at:
http://belgiantv.herokuapp.com

related tickets for old version of reactivemongo:
#224 and #109 (both closed)

```java
reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on heroku_app####.broadcasts' (code = 13)]
        at reactivemongo.core.errors.ReactiveMongoException$.apply(errors.scala:32)
        at reactivemongo.core.protocol.Response.error$lzycompute(protocol.scala:270)
        at reactivemongo.core.protocol.Response.error(protocol.scala:265)
        at reactivemongo.core.actors.MongoDBSystem$$anonfun$6.applyOrElse(actors.scala:479)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at reactivemongo.core.actors.LegacyDBSystem.aroundReceive(actors.scala:744)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

heroku logs

```
2015-07-19T03:36:05.588619+00:00 heroku[web.1]: Idling
2015-07-19T03:36:05.589846+00:00 heroku[web.1]: State changed from up to down
2015-07-19T03:36:09.398450+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2015-07-19T03:36:10.469251+00:00 app[web.1]: [info]    application        - ReactiveMongoApi stopping...
2015-07-19T03:36:10.902153+00:00 app[web.1]: [info]    application        - ReactiveMongoApi connections stopped. [Success(Closed)]
2015-07-19T03:36:11.261867+00:00 app[web.1]: [info]    p.a.l.c.ActorSystemProvider - Shutdown application default Akka system: application
2015-07-19T03:36:13.700463+00:00 heroku[web.1]: Process exited with status 143
2015-07-19T09:58:53.678798+00:00 heroku[web.1]: Unidling
2015-07-19T09:58:53.679264+00:00 heroku[web.1]: State changed from down to starting
2015-07-19T09:59:00.667154+00:00 heroku[web.1]: Starting process with command `target/universal/stage/bin/belgiantv -Dhttp.port=${PORT} -Dconfig.resource=prod.conf`
2015-07-19T09:59:02.964442+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx384m -Xss512k -Dfile.encoding=UTF-8
2015-07-19T09:59:07.307126+00:00 app[web.1]: [info]    p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
2015-07-19T09:59:07.861158+00:00 app[web.1]: [info]    application        - Scheduling actor trigger
2015-07-19T09:59:08.526273+00:00 app[web.1]: [info]    play.api.Play      - Application started (Prod)
2015-07-19T09:59:09.108284+00:00 heroku[web.1]: State changed from starting to up
2015-07-19T09:59:08.993440+00:00 app[web.1]: [info]    p.c.s.NettyServer  - Listening for HTTP on /0:0:0:0:0:0:0:0:39981
2015-07-19T09:59:12.941466+00:00 app[web.1]: [info]    application        - ReactiveMongoApi starting...
2015-07-19T09:59:13.404215+00:00 app[web.1]: [info]    application        - ReactiveMongoApi successfully started with DB 'heroku_app4877663'! Servers:
2015-07-19T09:59:13.404220+00:00 app[web.1]: 		[ds033297.mongolab.com:33297]
2015-07-19T09:59:15.560151+00:00 app[web.1]: [error]   application        - Server error: /
2015-07-19T09:59:15.560158+00:00 app[web.1]: reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on heroku_app4877663.broadcasts' (code = 13)]
2015-07-19T09:59:15.560160+00:00 app[web.1]: 	at reactivemongo.core.errors.ReactiveMongoException$.apply(errors.scala:32) ~[org.reactivemongo.reactivemongo_2.11-0.11.2.jar:0.11.2]
2015-07-19T09:59:15.560161+00:00 app[web.1]: 	at reactivemongo.core.protocol.Response.error$lzycompute(protocol.scala:270) ~[org.reactivemongo.reactivemongo_2.11-0.11.2.jar:0.11.2]
2015-07-19T09:59:15.560163+00:00 app[web.1]: 	at reactivemongo.core.protocol.Response.error(protocol.scala:265) ~[org.reactivemongo.reactivemongo_2.11-0.11.2.jar:0.11.2]
2015-07-19T09:59:15.560164+00:00 app[web.1]: 	at reactivemongo.core.actors.MongoDBSystem$$anonfun$6.applyOrElse(actors.scala:479) ~[org.reactivemongo.reactivemongo_2.11-0.11.2.jar:0.11.2]
2015-07-19T09:59:15.560166+00:00 app[web.1]: 	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[org.scala-lang.scala-library-2.11.7.jar:na]
2015-07-19T09:59:15.864805+00:00 app[web.1]: [error]   application        -
2015-07-19T09:59:15.864813+00:00 app[web.1]: ! @6moilh8h0 - Internal server error, for (GET) [/] ->
2015-07-19T09:59:15.864810+00:00 app[web.1]:
2015-07-19T09:59:15.864816+00:00 app[web.1]: play.api.UnexpectedException: Unexpected exception[DetailedDatabaseException: DatabaseException['not authorized for query on heroku_app4877663.broadcasts' (code = 13)]]
2015-07-19T09:59:15.864814+00:00 app[web.1]:
2015-07-19T09:59:15.864820+00:00 app[web.1]: 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
2015-07-19T09:59:15.864818+00:00 app[web.1]: 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
2015-07-19T09:59:15.864826+00:00 app[web.1]: Caused by: reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on heroku_app4877663.broadcasts' (code = 13)]
2015-07-19T09:59:15.864823+00:00 app[web.1]: 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
2015-07-19T09:59:15.864821+00:00 app[web.1]: 	at global.ErrorReportingHttpErrorHandler.onServerError(ErrorReportingHttpErrorHandler.scala:30) [belgiantv.belgiantv-1.0-SNAPSHOT-sans-externalized.jar:na]
2015-07-19T09:59:15.864825+00:00 app[web.1]: 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
2015-07-19T09:59:15.864828+00:00 app[web.1]: 	at reactivemongo.core.errors.ReactiveMongoException$.apply(errors.scala:32) ~[org.reactivemongo.reactivemongo_2.11-0.11.2.jar:0.11.2]
2015-07-19T09:59:15.864830+00:00 app[web.1]: 	at reactivemongo.core.protocol.Response.error$lzycompute(protocol.scala:270) ~[org.reactivemongo.reactivemongo_2.11-0.11.2.jar:0.11.2]
2015-07-19T09:59:15.864831+00:00 app[web.1]: 	at reactivemongo.core.protocol.Response.error(protocol.scala:265) ~[org.reactivemongo.reactivemongo_2.11-0.11.2.jar:0.11.2]
2015-07-19T09:59:15.864833+00:00 app[web.1]: 	at reactivemongo.core.actors.MongoDBSystem$$anonfun$6.applyOrElse(actors.scala:479) ~[org.reactivemongo.reactivemongo_2.11-0.11.2.jar:0.11.2]
2015-07-19T09:59:15.864834+00:00 app[web.1]: 	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[org.scala-lang.scala-library-2.11.7.jar:na]
2015-07-19T09:59:15.929831+00:00 heroku[router]: at=info method=GET path="/" host=belgiantv.herokuapp.com request_id=6b8798a9-81f6-4eb7-88ef-e4af93450520 fwd="78.21.183.24" dyno=web.1 connect=1ms service=4144ms status=500 bytes=2296
2015-07-19T09:59:25.415507+00:00 heroku[router]: at=info method=GET path="/" host=belgiantv.herokuapp.com request_id=a9ff526e-7e37-42a7-be66-e4dfe787ef72 fwd="78.21.183.24" dyno=web.1 connect=1ms service=1022ms status=200 bytes=115084
```

**Comment by cchantep** [comment]
As soon as it can't be reproduced, w/ heroku & mongolab, I suggest you move it to the MailingList and/or Heroku support. Best regards.

**Comment by francisdb** [comment]
feel free to close this issue if you think it's not related to reactivemongo, It's not that big an issue for me as this is just a hobby project.

**Comment by caeus** [comment]
I think it is related to reactivemongo. It happens in my local server when restarting (connecting to a remote mongodb (mongolab))

**Comment by francisdb** [comment]
Seems to be a permanent problem now that mongolab switched to mongod version: 3.0.6

**Comment by cchantep** [comment]
Hi, As for MongoDB 3, I can confirmed that ReactiveMongo is compatible with, either on legacy mode or with fresh install (e.g. WiredTiger, SCRAM-SHA). Please move this discussion, with more detailed test case on the MailingList, until there is confirmed issue. Thanks.
