### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException on update with mongo 2.4.12

### ISSUE THREAD

**Issue by pkudinov** [ReactiveMongo/ReactiveMongo#394]
I'm migrating my app from play 2.3.9 reactivemongo 0.10.5 to play 2.4 and reactivemongo 0.11.6

Reading from db works fine. But I cannot update any document or even insert with JSONCollection (this [line](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/api/serializationpack.scala#L31) throws exception). In my case `buf` has length 101 and `buf.readerIndex` is also equal to 101.

Everything works fine with latest mongo.
I'm not sure where should I post this, but it looks like a bug to me, so I'm posting it here.

Log with TRACE level:
 
```
2015-08-11_16:21:13 DEBUG r.core.actors.MongoDBSystem [utils.scala:44] - received a checked write request
2015-08-11_16:21:15 DEBUG r.core.actors.MongoDBSystem [utils.scala:44] - Sending request expecting response Request(3059,0,Update(rush.accounts,0),BufferSequence(DynamicChannelBuffer(ridx=0, widx=406, cap=512),WrappedArray()),reactivemongo.api.ReadPreference$Primary$@76b5c9e6,None) by connection Connection([id: 0x8840831c, /127.0.0.1:60064 => localhost/127.0.0.1:27018],Connected,Set(),None) of node localhost:27018
2015-08-11_16:21:15 TRACE r.core.actors.MongoDBSystem [utils.scala:42] - registering writeConcern-awaiting response for requestID 3059, awaitingResponses: Map(3059 -> AwaitingResponse(3059,-2009038052,scala.concurrent.impl.Promise$DefaultPromise@1b695a76,true,false))
2015-08-11_16:21:15 TRACE r.core.protocol.MongoHandler [utils.scala:42] - (channel=-2009038052) a write is requested!
2015-08-11_16:21:15 TRACE r.core.protocol.MongoHandler [utils.scala:42] - (channel=-2009038052) a write is requested!
2015-08-11_16:21:15 TRACE r.core.protocol.MongoHandler [utils.scala:42] - (channel=-2009038052) a write is complete!
2015-08-11_16:21:15 DEBUG r.core.actors.MongoDBSystem [utils.scala:44] - ConnectAll Job running... Status: Node[localhost:27018: Primary (10/10 available connections), latency=2059], auth=Set()
2015-08-11_16:21:15 DEBUG r.core.actors.MongoDBSystem [utils.scala:44] - ConnectAll Job running... Status: Node[localhost:27018: Primary (10/10 available connections), latency=2059], auth=Set()
2015-08-11_16:21:15 DEBUG r.core.actors.MongoDBSystem [utils.scala:44] - ConnectAll Job running... Status: Node[localhost:27018: Primary (10/10 available connections), latency=2059], auth=Set()
2015-08-11_16:21:15 TRACE r.core.protocol.MongoHandler [utils.scala:42] - (channel=-2009038052) messageReceived Response(MessageHeader(101,1348,3059,1),Reply(8,0,0,1),LittleEndianHeapChannelBuffer(ridx=36, widx=101, cap=101),ResponseInfo(-2009038052)) will be send to Actor[akka://reactivemongo/user/Connection-44#-1026316911]
2015-08-11_16:21:15 DEBUG r.core.actors.MongoDBSystem [utils.scala:44] - Got a response from -2009038052! Will give back message=Response(MessageHeader(101,1348,3059,1),Reply(8,0,0,1),LittleEndianHeapChannelBuffer(ridx=36, widx=101, cap=101),ResponseInfo(-2009038052)) to promise scala.concurrent.impl.Promise$DefaultPromise@1b695a76
2015-08-11_16:21:15 DEBUG r.core.actors.MongoDBSystem [utils.scala:44] - {3059} it's a getlasterror
2015-08-11_16:21:19 TRACE r.core.actors.MongoDBSystem [utils.scala:42] - {3059} sending a success (lasterror is ok)
2015-08-11_16:25:37 TRACE reactivemongo.api.Failover2 [utils.scala:43] - Got an non retryable error, completing with a failure...
java.lang.ArrayIndexOutOfBoundsException: 101
	at org.jboss.netty.buffer.LittleEndianHeapChannelBuffer.getInt(LittleEndianHeapChannelBuffer.java:69) ~[netty-3.10.3.Final.jar:na]
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:31) ~[reactivemongo_2.11-0.11.5.jar:0.11.5]
	at play.modules.reactivemongo.json.JSONSerializationPack$.readAndDeserialize(json.scala:351) ~[play2-reactivemongo_2.11-0.11.5.play24.jar:0.11.5.play24]
	at reactivemongo.api.collections.GenericCollection$$anonfun$update$1$$anonfun$apply$14.apply(genericcollection.scala:314) ~[reactivemongo_2.11-0.11.5.jar:0.11.5]
	at reactivemongo.api.collections.GenericCollection$$anonfun$update$1$$anonfun$apply$14.apply(genericcollection.scala:313) ~[reactivemongo_2.11-0.11.5.jar:0.11.5]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[scala-library-2.11.6.jar:na]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.6.jar:na]
	at scala.util.Success.map(Try.scala:236) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.6.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
2015-08-11_16:25:37 ERROR p.c.s.n.PlayDefaultUpstreamHandler [PlayDefaultUpstreamHandler.scala:271] - Cannot invoke the action
java.lang.ArrayIndexOutOfBoundsException: 101
	at org.jboss.netty.buffer.LittleEndianHeapChannelBuffer.getInt(LittleEndianHeapChannelBuffer.java:69) ~[netty-3.10.3.Final.jar:na]
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:31) ~[reactivemongo_2.11-0.11.5.jar:0.11.5]
	at play.modules.reactivemongo.json.JSONSerializationPack$.readAndDeserialize(json.scala:351) ~[play2-reactivemongo_2.11-0.11.5.play24.jar:0.11.5.play24]
	at reactivemongo.api.collections.GenericCollection$$anonfun$update$1$$anonfun$apply$14.apply(genericcollection.scala:314) ~[reactivemongo_2.11-0.11.5.jar:0.11.5]
	at reactivemongo.api.collections.GenericCollection$$anonfun$update$1$$anonfun$apply$14.apply(genericcollection.scala:313) ~[reactivemongo_2.11-0.11.5.jar:0.11.5]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[scala-library-2.11.6.jar:na]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.6.jar:na]
	at scala.util.Success.map(Try.scala:236) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.6.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
```

**Comment by cchantep** [comment]
> Everything works fine with latest mongo.

What do you mean? With which MongoDB version is there the issue?

**Comment by pkudinov** [comment]
Ah, sorry, didn't put it to the body. It is mongo 2.4.12

**Comment by cchantep** [comment]
ReactiveMongo no longer supports MongoDB 2.4, as its [EOL was reached last April](https://www.mongodb.com/support-policy). For further question, you can use the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo). Best regards.

**Comment by arescope** [comment]
So @cchantep, we asume that 0.10.X is partially compatible with Mongo 3.0 and 0.11.x is 2.6+ compatible.

So anyone that is planing to upgrade from MongoDB 2.4 to 3.0 is really fucked up. Unless having downtime (what is not an option) or upgrading first to 2.6 (that  we assume 0.10.5 is working fine) and then update reactivemongo to 0.11.x, which is not trivial because you have made a lot of changes.

I am right?

**Comment by cchantep** [comment]
0.10.5 is partially compatible with MongoDB 3 (not 0.10). It's still possible to stay with older version of ReactiveMongo, but to go on with the newer one, it's necessary to consider to MongoDB compatibility and EOL policy. It's not possible maintain endlessly code for DB version which are not even longer supported by MongoDB themselves.

As indicated, please use the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo), rather than this issue tracker, to ask for such questions.

Best regards.

**Comment by danmassie** [comment]
EOL for MongoDB 2.4 is March 2016 so I'm surprised that ReactiveMongo has already ceased support for it.

**Comment by cchantep** [comment]
Hi, this is something that can be discussed on the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) (not on this issue tracker). BTW (as said before) there is no plan to get back a full support for 2.4. Best regards.
