### ISSUE TITLE
Error message after adding new field

### ISSUE THREAD

**Issue by doubaokun** [ReactiveMongo/ReactiveMongo#401]
The json and bson mapping used reactivemongo.bson.Macros, after added new field by run command in mongodb console: db.items.update({}, { $set: { "new_field": 1}}, { multi: true}), the new field also added in the case class, but get the following error message:

```
object BsonJsonProtocol {
  import reactivemongo.bson.Macros
  implicit val myItemBsonFormat = Macros.handler[MyItem]
}
```
```
java.lang.RuntimeException: reactivemongo.bson.BSONDouble cannot be cast to reactivemongo.bson.BSONInteger
        at scala.sys.package$.error(package.scala:27)
        at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:355)
        at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:348)
        at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670)
        at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by cchantep** [comment]
Hi @doubaokun , please use the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask questions. Best regards.
