### ISSUE TITLE
Exception on invalid database name

### ISSUE THREAD

**Issue by thwiegan** [ReactiveMongo/ReactiveMongo#420]
If you provide an invalid database name to the reactive mongo driver (e.g. one containing a "."), there is no exception thrown. But any write operation throws:

`java.lang.IndexOutOfBoundsException: Not enough readable bytes - Need 4, maximum is 0
	at org.jboss.netty.buffer.EmptyChannelBuffer.checkReadableBytes(EmptyChannelBuffer.java:210)
	at org.jboss.netty.buffer.AbstractChannelBuffer.readInt(AbstractChannelBuffer.java:273)
	at reactivemongo.core.netty.ChannelBufferReadableBuffer.readInt(netty.scala:39)
	at reactivemongo.bson.lowlevel.LoweLevelDocumentIterator$$anon$1.next(lowlevel.scala:32)
	at reactivemongo.bson.lowlevel.LoweLevelDocumentIterator$$anon$1.next(lowlevel.scala:28)
	at reactivemongo.api.commands.Command$$anon$2$$anonfun$one$1$$anonfun$apply$1.apply(commands.scala:95)
	at reactivemongo.api.commands.Command$$anon$2$$anonfun$one$1$$anonfun$apply$1.apply(commands.scala:93) `

Took me a couple of hours to figure out what the actual error was. An exception on driver initialization would probably make sense?

**Comment by cchantep** [comment]
Hi, thanks for reporting. Please indicate which versions you are using.
