### ISSUE TITLE
Aggregate Command with Cursor Doesn't Work

### ISSUE THREAD

**Issue by fdoumet** [ReactiveMongo/ReactiveMongo#444]
Calling Aggregate with a Cursor parameter as below:

````
def sumPerUser(appId: String, date: DateTime): Future[Seq[UserImpressionSums]] = {
import collection.BatchCommands.AggregationFramework._

collection.aggregate(
  Match(BSONDocument(APP_ID -> appId, DATE_CREATED -> BSONDocument("$gte" -> BSONDateTime(date.getMillis)))),
  List(Project(BSONDocument(USER -> 1, DATE_CREATED -> 1, IP -> 1, CAMPAIGN_ID -> 1, "imp" -> BSONDocument("$literal" -> 1) )),
    Group(BSONDocument(USER -> "$user", IP -> "$ip", CAMPAIGN_ID -> "$campaign_id"))
    ("totalImps" -> SumField("imp"), DATE_CREATED -> First(DATE_CREATED)),
    Sort(Ascending(DATE_CREATED))
  ), false, true, Some(Cursor(100)))

  .map(_.result[UserImpressionSums])
}}
````

throws an exception upon execution:

````
reactivemongo.api.commands.bson.DefaultBSONCommandError: CommandError[code=14, errmsg=cursor field must be missing or an object, doc: {
  ok: BSONDouble(0.0),
  errmsg: "cursor field must be missing or an object",
  code: BSONInteger(14)
}]
````

Digging deeper, the cursor isn't being serialized properly. In `Aggregation.scala`, cursor should be serialized as
`"cursor" -> agg.command.cursor.map(c =>BSONDocument("batchSize" -> BSONInteger(batchSize)`
instead of
 `"cursor" -> agg.command.cursor.map(c => BSONInteger(c.batchSize))`

But `ArggregationResult` should also be reworked to handle cursor results

**Comment by cchantep** [comment]
Hi, thanks for reporting. There is a serialization issue about that, but not only as it needs to add the cursor (not the aggregate option, but the read cursor). Working on it at the same time as #442 . Best regards.

**Comment by cchantep** [comment]
The fix can be tried with 0.12-SNAPSHOT

**Comment by fdoumet** [comment]
Some commands that used to work fine now have Futures that are timing out. Any idea why?

```
[error] r.api.Cursor - fails to send request
java.util.concurrent.TimeoutException: Futures timed out after [3000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$4.block(ExecutionContextImpl.scala:48) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Await$.ready(package.scala:169) ~[scala-library-2.11.7.jar:na]
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$awaitFailover$1.apply(cursor.scala:476) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$awaitFailover$1.apply(cursor.scala:476) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
```

**Comment by cchantep** [comment]
Please use the MailingList to discuss/give details.
