### ISSUE TITLE
reactive mongo OFTEN crashes with the following error 

### ISSUE THREAD

**Issue by gsaxam** [ReactiveMongo/ReactiveMongo#445]
--- (RELOAD) ---

[debug] - play.api.libs.concurrent.ActorSystemProvider - Shutdown application default Akka system: application
[debug] - play.api.libs.concurrent.ActorSystemProvider - Starting application default Akka system: application
[info] - play.api.Play - Application started (Dev)
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.api.Failover2 - Got an error, no more attempts to do. Completing with a failure...
reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$: MongoError['No primary node is available!']
        at reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$.<clinit>(actors.scala) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
   
at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:117) [reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.api.Failover2 - Got an error, no more attempts to do. Completing with a failure...
reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$: MongoError['No primary node is available!']
        at reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$.<clinit>(actors.scala) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2.reactivemongo$api$Failover2$$isRetryable(api.scala:140) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:118) [reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:117) [reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.api.Failover2 - Got an error, no more attempts to do. Completing with a failure...
reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$: MongoError['No primary node is available!']
        at reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$.<clinit>(actors.scala) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2.reactivemongo$api$Failover2$$isRetryable(api.scala:140) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:118) [reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:117) [reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.api.Failover2 - Got an error, no more attempts to do. Completing with a failure...
reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$: MongoError['No primary node is available!']
        at reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$.<clinit>(actors.scala) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2.reactivemongo$api$Failover2$$isRetryable(api.scala:140) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:118) [reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:117) [reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
[error] - reactivemongo.api.Failover2 - Got an error, no more attempts to do. Completing with a failure...
reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$: MongoError['No primary node is available!']
        at reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$.<clinit>(actors.scala) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2.reactivemongo$api$Failover2$$isRetryable(api.scala:140) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:118) [reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:117) [reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
[error] - akka.dispatch.Dispatcher - MongoError['No primary node is available!']
reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$: MongoError['No primary node is available!']
        at reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$.<clinit>(actors.scala) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2.reactivemongo$api$Failover2$$isRetryable(api.scala:140) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:118) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at reactivemongo.api.Failover2$$anonfun$reactivemongo$api$Failover2$$send$2.apply(api.scala:117) ~[reactivemongo_2.11-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) ~[scala-library-2.11.6.jar:na]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) ~[akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?
[error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?

**Comment by cchantep** [comment]
Hi, please use the MailingList to ask question (rather than this issue tracker).

I suggest you have a look at the [related discussion](https://groups.google.com/d/msg/reactivemongo/x3OZ6-hIIXk/c-CX4MlWEQAJ).

Best regards.
