### ISSUE TITLE
Lower to TRACE the first PrimaryUnavailableException (out of the 5 retries)

### ISSUE THREAD

**Issue by Antwnis** [ReactiveMongo/ReactiveMongo#490]
The http://stackoverflow.com/questions/29637238/successful-crud-but-for-lasterror-in-play-reactivemongo-2-3-8 is another testimony of this

In my case i upgraded my spray/reactivemongo to akka-http/reactivemongo and ended up having

    2016-03-14 20:19:04 DEBUG r.c.a.MongoDBSystem:44 - received a request expecting a response
    2016-03-14 20:19:04 DEBUG r.c.a.MongoDBSystem:44 - NO CHANNEL, error with promise scala.concurrent.impl.Promise$DefaultPromise@26d62bd
    2016-03-14 20:19:04 DEBUG r.a.Failover2:45 - Got an error, retrying... (try #1 is scheduled in 500 ms)
    reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$: MongoError['No primary node is available!']
            at reactivemongo.core.actors.Exceptions$PrimaryUnavailableException$.<clinit>(actors.scala) ~[reactivemongo_2.11-0.11.9.jar:0.11.9]
            at reactivemongo.core.actors.MongoDBSystem$$anonfun$reactivemongo$core$actors$MongoDBSystem$$pickChannel$4.apply(actors.scala:681) ~[reactivemongo_2.11-    0.11.9.jar:0.11.9]
            at reactivemongo.core.actors.MongoDBSystem$$anonfun$reactivemongo$core$actors$MongoDBSystem$$pickChannel$4.apply(actors.scala:681) ~[reactivemongo_2.11-    0.11.9.jar:0.11.9]
            at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:0.13.7]
            at reactivemongo.core.actors.MongoDBSystem$class.reactivemongo$core$actors$MongoDBSystem$$pickChannel(actors.scala:681) ~[reactivemongo_2.11-0.11.9.    jar:0.11.9]
            at reactivemongo.core.actors.MongoDBSystem$$anonfun$4.applyOrElse(actors.scala:335) ~[reactivemongo_2.11-0.11.9.jar:0.11.9]
            at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.7.jar:0.13.7]
            at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.2.jar:na]
            at reactivemongo.core.actors.LegacyDBSystem.aroundReceive(actors.scala:796) ~[reactivemongo_2.11-0.11.9.jar:0.11.9]
            at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.2.jar:na]
            at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.2.jar:na]
            at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.2.jar:na]
            at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.2.jar:na]
            at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.11-2.4.2.jar:na]
            at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
            at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
            at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
            at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
    2016-03-14 20:19:04 INFO  r.c.a.MongoDBSystem:46 - The node set is now available
    2016-03-14 20:19:04 INFO  r.c.a.MongoDBSystem:46 - The primary is now available
    2016-03-14 20:19:04 DEBUG r.c.a.MonitorActor:44 - set: a node is available: ProtocolMetadata(reactivemongo.core.protocol.    MongoWireVersion$V24AndBefore$@52a99515,reactivemongo.core.protocol.MongoWireVersion$V26$@3cb7cdf2,16777216,48000000,1000)
    2016-03-14 20:19:04 DEBUG r.c.a.MonitorActor:44 - set: a primary is available
    2016-03-14 20:19:05 DEBUG r.c.a.MongoDBSystem:44 - received a request expecting a response 

Of course the 2nd retry always succeeds !

So this 1st occurrence should be **TRACE** level as we - developers care too much and get alerted even for DEBUG messages

Thanks!

**Comment by cchantep** [comment]
Hi,

The last minor releases are using SFL4J, so you can filter ReactiveMongo as you want.

Best regards

> BTW as indicated in the guide lines, please first ask on the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo).
