### ISSUE TITLE
Something wrong with authentication in dev mode?

### ISSUE THREAD

**Issue by brianwawok** [ReactiveMongo/ReactiveMongo#61]
I see this a lot in dev mode.. never seen it in prod mode..  I can't save stuff to a database I clearly have permission to save to (i.e. it works 10% of the time)

Dev mode = windows 7 machine
Prod mode = ubuntu

Database: Mongo 2.4.1

[error] application - Unable to log user in. An exception was thrown
reactivemongo.core.commands.LastError: MongoError['not authorized for insert on myMongoDb.Authentications' (code = 1654
4)]
        at reactivemongo.core.commands.LastError$.apply(commands.scala:233) ~[reactivemongo_2.10-0.8.jar:0.8]
        at reactivemongo.core.commands.LastError$.apply(commands.scala:231) ~[reactivemongo_2.10-0.8.jar:0.8]
        at reactivemongo.core.commands.BSONCommandResultMaker$class.apply(commands.scala:61) ~[reactivemongo_2.10-0.8.ja
r:0.8]
        at reactivemongo.core.commands.LastError$.apply(commands.scala:231) ~[reactivemongo_2.10-0.8.jar:0.8]
        at reactivemongo.core.commands.LastError$.meaningful(commands.scala:242) ~[reactivemongo_2.10-0.8.jar:0.8]
        at reactivemongo.api.FailoverBasicCollection$$anonfun$insert$1.apply(collection.scala:303) ~[reactivemongo_2.10-
0.8.jar:0.8]

**Comment by andy-b-84** [comment]
Sorry to wake this old thread, but I'm encountering a similar issue, using "org.reactivemongo" %% "play2-reactivemongo" % "0.11.5.play24", running on an AWS EC2 red hat machine :$ uname -a
Linux ip-10-253-3-102 4.4.11-23.53.amzn1.x86_64 #1 SMP Wed Jun 1 22:22:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux , )

**Comment by cchantep** [comment]
Hi @andy-b-84, I suggest you first have a look at the [documentation](http://reactivemongo.org/releases/0.11/documentation/tutorial/connect-database.html) (specially to `authMode`/SCRAM-SHA-1), then possibly to have a look at the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo), which is the place to ask questions/for help (this tracker is for confirmed issue/actionable request). Best regards
