### ISSUE TITLE
AbstractMethodError during initialization on Windows 10

### ISSUE THREAD

**Issue by ghik** [ReactiveMongo/ReactiveMongo#780]
### ReactiveMongo Version

0.16.0

### MongoDB version

4.0

### Operating System

Windows 10

### JDK

Oracle 1.8.0_181

### Expected Behavior

No crash

### Actual Behavior

Application crashes when trying to initialize the driver:

```
Uncaught error from thread [reactivemongo-akka.actor.default-dispatcher-4]: reactivemongo.io.netty.util.internal.logging.Log4J2Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[reactivemongo]
java.lang.AbstractMethodError: reactivemongo.io.netty.util.internal.logging.Log4J2Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V
	at reactivemongo.io.netty.util.internal.PlatformDependent0.explicitNoUnsafeCause0(PlatformDependent0.java:376)
	at reactivemongo.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:42)
	at reactivemongo.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at reactivemongo.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at reactivemongo.io.netty.channel.ChannelInitializer.<init>(ChannelInitializer.java:58)
	at reactivemongo.core.nodeset.ChannelFactory.<init>(ChannelFactory.scala:42)
	at reactivemongo.core.actors.StandardDBSystem.newChannelFactory(MongoDBSystem.scala:1533)
	at reactivemongo.core.actors.MongoDBSystem.preStart(MongoDBSystem.scala:253)
	at reactivemongo.core.actors.MongoDBSystem.preStart$(MongoDBSystem.scala:250)
	at reactivemongo.core.actors.StandardDBSystem.preStart(MongoDBSystem.scala:1525)
	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
	at reactivemongo.core.actors.StandardDBSystem.aroundPreStart(MongoDBSystem.scala:1525)
	at akka.actor.ActorCell.create(ActorCell.scala:652)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### Reproducible Test Case

```scala
val driver = MongoDriver()
val connection = driver.connection(List("localhost"))
```

**Comment by cchantep** [comment]
As indicated in the [documentation](http://reactivemongo.org/releases/0.1x/documentation/tutorial/setup.html), you need to provide a SLF4J binding.

> Please rather use the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask for question.
