### ISSUE TITLE
Skip channel init as host is null 0.16.0

### ISSUE THREAD

**Issue by cvrnogueira** [ReactiveMongo/ReactiveMongo#789]
### Describing possible issue on  ReactiveMongo Version (0.16.0)

> We (@ivasmartins, @miguelbaldi and @maiconbaumx) are facing an issue that we could not find out how to solve it by our side.

We believe that this happens when we use native Netty dependency.

We are getting this probable issue described below within this characteristics:

_**1**. Flink services: Alpine with Java 8 and flink 1.6.1 with netty native dependencies. Mongo Version: 4.0.4-15-g7ad4f64
**2.** Microservices Services: Alpine with Java 8, 10 and 11 with shaded netty dependency. Mongo Version: 4.0.4-15-g7ad4f64_ 

### Actual Behavior

We expected that the message: "Skip channel init as host is null"  would not get into a warning message. 
Service keeps working and saving/getting infos from reactive mongo but this message keeps filling our logs and then our service dies due to excessive logs.

We believe that the log level is wrong, should not be WARN. And we do not understand why this happens as well.

### How we connect:

We connect on reactive mongo getting secrets from Vault. This is on a Scala class instantiated once on a object Application that extends App with StrictLogging.

> Below our MongoConfig class:

```
private lazy val servers: Seq[String] = config.getString("mongoNodes").split(",").toSeq
  private lazy val authDBName = config.getString("mongo.authDBName")
  private lazy val password = VaultConfiguration.apply(config).getSecret(VaultRoot, VaultKey)

  private lazy val credentials = MongoConnectionOptions.Credential(config.getString("mongoUsername"), password = Some(password))
  private lazy val conOpts = MongoConnectionOptions(credentials = Map((authDBName, credentials)))
  private lazy val connection = driver1.connection(servers, options = conOpts)

  private lazy val dataDBName = config.getString("mongo.dataDBName")
  private lazy val collectionNameOne = config.getString("mongo.collectionOne")
  private lazy val collectionNameTwo = config.getString("mongo.collectionTwo")

  def collectionOne: Future[BSONCollection] =
    connection.database(dataDBName).
      map(_.collection(collectionNameOne ))
```

### Logs when TRACE is enable

> This below kepps loggind and looping while service continues to work until te moments it dies for excessive logging

`
```
2018-12-27 12:01:44,005 TRACE reactivemongo.core.actors.MongoDBSystem - [Supervisor-7/Connection-10] Channel #f87d34d9 is unavailable

14:01:44
2018-12-27 12:01:44,005 TRACE reactivemongo.core.actors.MongoDBSystem - [Supervisor-7/Connection-10] Channel #f87d34d9 is released

14:01:44
2018-12-27 12:01:44,005 WARN reactivemongo.core.nodeset.ChannelFactory - [Supervisor-3/Connection-6] Skip channel init as host is null

14:01:44
2018-12-27 12:01:44,006 WARN reactivemongo.core.nodeset.ChannelFactory - [Supervisor-2/Connection-4] Skip channel init as host is null

14:01:44
2018-12-27 12:01:44,006 DEBUG reactivemongo.core.nodeset.ChannelFactory - [Supervisor-3/Connection-6] Created new channel #8d9afaf7 to mongo.connection.url:port (registered = true)

14:01:44
2018-12-27 12:01:44,006 DEBUG reactivemongo.core.nodeset.ChannelFactory - [Supervisor-3/Connection-6] Initializing channel 8d9afaf7 to mongo.connection.url:port (registered = true) (Actor[akka://reactivemongo/user/Connection-6#-1991067078])

14:01:44
2018-12-27 12:01:44,006 DEBUG reactivemongo.core.nodeset.ChannelFactory - [Supervisor-2/Connection-4] Created new channel #2814261e to mongo.connection.url:port (registered = true)

14:01:44
2018-12-27 12:01:44,006 DEBUG reactivemongo.core.nodeset.ChannelFactory - [Supervisor-2/Connection-4] Initializing channel 2814261e to mongo.connection.url:port (registered = true) (Actor[akka://reactivemongo/user/Connection-4#934737798])

14:01:44
2018-12-27 12:01:44,006 TRACE reactivemongo.core.nodeset.ChannelFactory - [Supervisor-3/Connection-6] Netty channel configuration:

14:01:44
- connectTimeoutMS: 0

14:01:44
- maxIdleTimeMS: 0ms

14:01:44
- tcpNoDelay: false

14:01:44
- keepAlive: false

14:01:44
- sslEnabled: false

14:01:44
- keyStore: None

14:0144
2018-12-27 12:01:44,006 TRACE reactivemongo.core.actors.MongoDBSystem - [Supervisor-3/Connection-6] Channel #c689d6e1 is unavailable

14:01:44
2018-12-27 12:01:44,006 TRACE reactivemongo.core.actors.MongoDBSystem - [Supervisor-3/Connection-6] Channel #c689d6e1 is released

14:01:44
2018-12-27 12:01:44,006 DEBUG reactivemongo.core.nodeset.ChannelFactory - [Supervisor-3/Connection-6] Created new channel #7a7c57df to mongo.connection.url:port (registered = false)

14:01:44
2018-12-27 12:01:44,006 TRACE reactivemongo.core.actors.MongoDBSystem - [Supervisor-3/Connection-6] Channel #9eae6956 is unavailable

14:01:44
2018-12-27 12:01:44,006 TRACE reactivemongo.core.actors.MongoDBSystem - [Supervisor-3/Connection-6] Channel #9eae6956 is released

14:01:44
2018-12-27 12:01:44,006 DEBUG reactivemongo.core.nodeset.ChannelFactory - [Supervisor-7/Connection-10] Connection to mongo.connection.url:port refused for channel #733b7618

14:01:44
reactivemongo.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: mongo.connection.url:port/127.0.0.01:port

14:01:44
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)

14:01:44
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)

14:01:44
at reactivemongo.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)

14:01:44
at reactivemongo.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)

14:01:44
at reactivemongo.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)

14:01:44
at reactivemongo.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)

14:01:44
at reactivemongo.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)

14:01:44
at reactivemongo.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)

14:01:44
at reactivemongo.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)

14:01:44
at reactivemongo.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

14:01:44
at java.lang.Thread.run(Thread.java:745)

14:01:44
Caused by: java.net.ConnectException: Connection refused

14:01:44
... 11 more`**
```

**Comment by cchantep** [comment]
Just a non fatal warning
