### ISSUE TITLE
NullPointerException when trying to save JsString(null)

### ISSUE THREAD

**Issue by devas123** [ReactiveMongo/ReactiveMongo#796]
I get a nullpointer exception when trying to save a JsObject with fields that are JsString(null). 
Looks like a bug to me.

### JDK Oracle
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

### Library Dependencies
"org.reactivemongo" %% "play2-reactivemongo" % "0.16.2-play26" in a simple Play application

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

an object should be saved.

### Actual Behavior

NullPointerException: 
`java.lang.NullPointerException: null
        at reactivemongo.bson.buffer.WritableBuffer.writeString(WritableBuffer.scala:53)
        at reactivemongo.bson.buffer.WritableBuffer.writeString$(WritableBuffer.scala:52)
        at reactivemongo.core.netty.ChannelBufferWritableBuffer.writeString(ChannelBufferWritableBuffer.scala:23)
        at reactivemongo.bson.buffer.DefaultBufferHandler$BSONStringBufferHandler$.write(DefaultBufferHandler.scala:69)
        at reactivemongo.bson.buffer.DefaultBufferHandler$BSONStringBufferHandler$.write(DefaultBufferHandler.scala:68)
        at reactivemongo.bson.buffer.DefaultBufferHandler$.serialize(DefaultBufferHandler.scala:24)
        at reactivemongo.bson.buffer.DefaultBufferHandler$BSONDocumentBufferHandler$.$anonfun$write$1(DefaultBufferHandler.scala:82)
        at scala.collection.immutable.Stream.foreach(Stream.scala:529)
        at reactivemongo.bson.buffer.DefaultBufferHandler$BSONDocumentBufferHandler$.write(DefaultBufferHandler.scala:79)
        at reactivemongo.bson.buffer.DefaultBufferHandler$BSONDocumentBufferHandler$.write(DefaultBufferHandler.scala:73)`

### Reproducible Test Case
1. Create a JsObject
  `val obj = Json.obj(
        "a" -> JsString(null),
        "b" -> "something"
      )`
3. Save object in the db e.g.
  ` Await.result(collection.flatMap(_.insert(ordered = true).one(obj)), 1.second)`

**Comment by cchantep** [comment]
It should be handled, but BTW `JsString(null)` is far from being recommended, and should never happend whatever is the context

**Comment by devas123** [comment]
`JsString(null)` is not good, i agree :) but still it should not cause an NPE, at least some meaningful exception, imho.
