### ISSUE TITLE
java.lang.IndexOutOfBoundsExceptio error on EmptyByteBuf

### ISSUE THREAD

**Issue by cvrnogueira** [ReactiveMongo/ReactiveMongo#820]
I am having a strange behavior that happens from nowhere.
The message below is accompanied by high use of memory; 
When the error starts, the memory use starts to become higher and then, when arriving in 90% of memory existent, the system shuts down.

I am using Kafka 1.0.0 and Flink 1.6.1 together with Scala. 
The only database that I communicate with is Mongo.
My version of ReactiveMongo is 0.16.0. 
I do not use Netty library, just the one that comes together with ReactiveMongo.
I have a custom Failover strategy to connect with mongo.

I have this error from a long time and I do not know more what to do, I wish someone could help me to find whether is a Bug or something non-obvious to put on the connection.

`[ERROR] [05/02/2019 09:30:03.048] [reactivemongo-akka.actor.default-dispatcher-3] [akka://reactivemongo/user/Connection-36] null
java.lang.IndexOutOfBoundsException
at reactivemongo.io.netty.buffer.EmptyByteBuf.readIntLE(EmptyByteBuf.java:586)
at reactivemongo.core.netty.ChannelBufferReadableBuffer.readInt(ChannelBufferReadableBuffer.scala:41)
at reactivemongo.bson.buffer.DefaultBufferHandler$BSONDocumentBufferHandler$.read(DefaultBufferHandler.scala:87)
at reactivemongo.bson.buffer.DefaultBufferHandler$$anonfun$readDocument$1.apply(DefaultBufferHandler.scala:290)
at reactivemongo.bson.buffer.DefaultBufferHandler$$anonfun$readDocument$1.apply(DefaultBufferHandler.scala:290
at scala.util.Try$.apply(Try.scala:192)
at reactivemongo.bson.buffer.DefaultBufferHandler$.readDocument(DefaultBufferHandler.scala:290)
at reactivemongo.api.BSONSerializationPack$.readFromBuffer(BSONSerializationPack.scala:40
at reactivemongo.api.BSONSerializationPack$.readFromBuffer(BSONSerializationPack.scala:13)
at reactivemongo.api.SerializationPack$class.readAndDeserialize(SerializationPack.scala:36)
at reactivemongo.api.BSONSerializationPack$.readAndDeserialize(BSONSerializationPack.scala:13)
at reactivemongo.api.BSONSerializationPack$.readAndDeserialize(BSONSerializationPack.scala:55)
at reactivemongo.core.actors.MongoDBSystem$class.reactivemongo$core$actors$MongoDBSystem$$onIsMaster(MongoDBSystem.scala:905)
at reactivemongo.core.actors.MongoDBSystem$$anonfun$2.applyOrElse(MongoDBSystem.scala:6
at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170
at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
at reactivemongo.core.actors.StandardDBSystem.aroundReceive(MongoDBSystem.scala:1525)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
at akka.actor.ActorCell.invoke(ActorCell.scala:495)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
at akka.dispatch.Mailbox.run(Mailbox.scala:224)
at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

Thanks a lot! :-)

**Comment by cchantep** [comment]
Hi,

This issue tracker is for confirmed/actionable issue. Please use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question.

BTW without information to reproduce locally the issue (with all the versions, including those of the services), it's hard to have a specific answer.
